FROM python:3.9-slim

WORKDIR /code

COPY trip_plan.py /code/trip_plan.py
COPY requirements.txt /code/requirements.txt

RUN pip install -r /code/requirements.txt 

CMD ["uvicorn", "trip_plan:app", "--host", "0.0.0.0", "--port", "80"]
